### PR TITLE
Updated the Title

### PR DESCRIPTION
**Pull request by devarshishimpi**
Lol, Collab Community wasn't changed!

@Arindam200 @samyabrata-maji @Swpn0neel @priyankarpal

### CODE REVIEW

**Comment by samyabrata-maji** [comment]
@Arindam200 ☕

**Comment by devarshishimpi** [comment]
😂 @Arindam200 @samyabrata-maji

**Comment by Swpn0neel** [comment]
When you copy your friend's name while cheating during the exam 🤣🤣🤣. Moment.

**Comment by devarshishimpi** [comment]
lol

**Comment by sammaji** [comment]
😂

**Comment by priyankarpal** [comment]
😆

**Pull request merged**
